version: "3.3"

services:
  db:
    image: "warm-db:${BRANCH_TAG}"
    container_name: "db-runner-${BRANCH_TAG}"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "thunder"
      MYSQL_USER: "thunder"
      MYSQL_PASSWORD: "thunder"
    command: ["--secure-file-priv=/tmp", "--datadir=/var/lib/mysql-db"]
  chrome:
    image: "selenium/standalone-chrome:3.141.59-oxygen"
  thunder-php:
    image: "warm-thunder-php:${BRANCH_TAG}"
    container_name: "thunder-php-runner-${BRANCH_TAG}"
    command: ["su", "-", "thunder", "thunder-php-test"]
    ports:
      - "8080:8080"
